const captable = {
  convertibleNote: {
    conversionRound: {
      'next-preferred': 'Next Preferred',
    },
  },
  safe: {
    conversionRound: {
      'next-preferred': 'Next Preferred',
    },
  },
  preferredRound: {
    participation: {
      participating: 'Participating',
      nonParticipating: 'Non-Participating',
    },
    antiDilution: {
      none: 'None',
      weightedAverage: 'Weighted Average',
      fullRatchet: 'Full Ratchet',
    },
    dividendType: {
      simple: 'Simple',
      compound: 'Compound',
    },
  },
};

const revenue = {};

const models = {
  currencys: {
    EUR: { legend: 'EUR (Euro)', format: '' },
    USD: { legend: 'USD (US Dollar)', format: 'en-US' },
    AED: { legend: 'AED (Arab Emirates Dirham)', format: '' },
    AFN: { legend: 'AFN (Afghanistan Afghani)', format: '' },
    ALL: { legend: 'ALL (Albanian Lek)', format: '' },
    AMD: { legend: 'AMD (Armenian Dram)', format: '' },
    ANG: { legend: 'ANG (Netherlands Antillean Guilder)', format: '' },
    AOA: { legend: 'AOA (Angolan Kwanza)', format: '' },
    ARS: { legend: 'ARS (Argentine Peso)', format: '' },
    AUD: { legend: 'AUD (Australian Dollar)', format: '' },
    AWG: { legend: 'AWG (Aruban Guilder)', format: '' },
    AZN: { legend: 'AZN (Azerbaijan New Manat)', format: '' },
    BAM: { legend: 'BAM (Marka)', format: '' },
    BBD: { legend: 'BBD (Barbados Dollar)', format: '' },
    BDT: { legend: 'BDT (Bangladeshi Taka)', format: '' },
    BGN: { legend: 'BGN (Bulgarian Lev)', format: '' },
    BHD: { legend: 'BHD (Bahraini Dinar)', format: '' },
    BIF: { legend: 'BIF (Burundi Franc)', format: '' },
    BMD: { legend: 'BMD (Bermudian Dollar)', format: '' },
    BND: { legend: 'BND (Brunei Dollar)', format: '' },
    BOB: { legend: 'BOB (Boliviano)', format: '' },
    BRL: { legend: 'BRL (Brazilian Real)', format: '' },
    BSD: { legend: 'BSD (Bahamian Dollar)', format: '' },
    BTN: { legend: 'BTN (Bhutan Ngultrum)', format: '' },
    BWP: { legend: 'BWP (Botswana Pula)', format: '' },
    BYR: { legend: 'BYR (Belarussian Ruble)', format: '' },
    BZD: { legend: 'BZD (Belize Dollar)', format: '' },
    CAD: { legend: 'CAD (Canadian Dollar)', format: '' },
    CDF: { legend: 'CDF (Francs)', format: '' },
    CHF: { legend: 'CHF (Swiss Franc)', format: '' },
    CLP: { legend: 'CLP (Chilean Peso)', format: '' },
    CNY: { legend: 'CNY (Chinese Yuan Renminbi)', format: '' },
    COP: { legend: 'COP (Colombian Peso)', format: '' },
    CRC: { legend: 'CRC (Costa Rican Colon)', format: '' },
    CUP: { legend: 'CUP (Cuban Peso)', format: '' },
    CVE: { legend: 'CVE (Cape Verde Escudo)', format: '' },
    CZK: { legend: 'CZK (Czech Koruna)', format: '' },
    DJF: { legend: 'DJF (Djibouti Franc)', format: '' },
    DKK: { legend: 'DKK (Danish Krone)', format: '' },
    DOP: { legend: 'DOP (Dominican Peso)', format: '' },
    DZD: { legend: 'DZD (Algerian Dinar)', format: '' },
    ECS: { legend: 'ECS (Ecuador Sucre)', format: '' },
    EGP: { legend: 'EGP (Egyptian Pound)', format: '' },
    ERN: { legend: 'ERN (Eritrean Nakfa)', format: '' },
    ETB: { legend: 'ETB (Ethiopian Birr)', format: '' },
    FJD: { legend: 'FJD (Fiji Dollar)', format: '' },
    FKP: { legend: 'FKP (Falkland Islands Pound)', format: '' },
    GBP: { legend: 'GBP (British Pound Sterling)', format: '' },
    GEL: { legend: 'GEL (Georgian Lari)', format: '' },
    GGP: { legend: 'GGP (Guernsey Pound Sterling)', format: '' },
    GHS: { legend: 'GHS (Ghanaian Cedi)', format: '' },
    GIP: { legend: 'GIP (Gibraltar Pound)', format: '' },
    GMD: { legend: 'GMD (Gambian Dalasi)', format: '' },
    GNF: { legend: 'GNF (Guinea Franc)', format: '' },
    GWP: { legend: 'GWP (Guinea-Bissau Peso)', format: '' },
    GYD: { legend: 'GYD (Guyana Dollar)', format: '' },
    HKD: { legend: 'HKD (Hong Kong Dollar)', format: '' },
    HNL: { legend: 'HNL (Honduran Lempira)', format: '' },
    HRK: { legend: 'HRK (Croatian Kuna)', format: '' },
    HTG: { legend: 'HTG (Haitian Gourde)', format: '' },
    HUF: { legend: 'HUF (Hungarian Forint)', format: '' },
    IDR: { legend: 'IDR (Indonesian Rupiah)', format: '' },
    ILS: { legend: 'ILS (Israeli New Shekel)', format: '' },
    INR: { legend: 'INR (Indian Rupee)', format: '' },
    IQD: { legend: 'IQD (Iraqi Dinar)', format: '' },
    IRR: { legend: 'IRR (Iranian Rial)', format: '' },
    ISK: { legend: 'ISK (Iceland Krona)', format: '' },
    JMD: { legend: 'JMD (Jamaican Dollar)', format: '' },
    JOD: { legend: 'JOD (Jordanian Dinar)', format: '' },
    JPY: { legend: 'JPY (Japanese Yen)', format: '' },
    KES: { legend: 'KES (Kenyan Shilling)', format: '' },
    KGS: { legend: 'KGS (Som)', format: '' },
    KHR: { legend: 'KHR (Kampuchean Riel)', format: '' },
    KMF: { legend: 'KMF (Comoros Franc)', format: '' },
    KPW: { legend: 'KPW (North Korean Won)', format: '' },
    KRW: { legend: 'KRW (Korean Won)', format: '' },
    KWD: { legend: 'KWD (Kuwaiti Dinar)', format: '' },
    KYD: { legend: 'KYD (Cayman Islands Dollar)', format: '' },
    KZT: { legend: 'KZT (Kazakhstan Tenge)', format: '' },
    LAK: { legend: 'LAK (Lao Kip)', format: '' },
    LBP: { legend: 'LBP (Lebanese Pound)', format: '' },
    LKR: { legend: 'LKR (Sri Lanka Rupee)', format: '' },
    LRD: { legend: 'LRD (Liberian Dollar)', format: '' },
    LSL: { legend: 'LSL (Lesotho Loti)', format: '' },
    LTL: { legend: 'LTL (Lithuanian Litas)', format: '' },
    LVL: { legend: 'LVL (Latvian Lats)', format: '' },
    LYD: { legend: 'LYD (Libyan Dinar)', format: '' },
    MAD: { legend: 'MAD (Moroccan Dirham)', format: '' },
    MDL: { legend: 'MDL (Moldovan Leu)', format: '' },
    MGF: { legend: 'MGF (Malagasy Franc)', format: '' },
    MKD: { legend: 'MKD (Denar)', format: '' },
    MMK: { legend: 'MMK (Myanmar Kyat)', format: '' },
  },
};

export const optionsConfig = {
  captable,
  revenue,
  models,
};
